- experimental/cloudbuild/cloudbuild.yaml
- experimental/terraform/providers.tf
- experimental/terraform/resource_bigquery.tf
This will add the initial Cloud Build YAML file to execute Terraform code.
> Add initial Cloud Build yaml file to execute Terraform code

- experimental/cloudbuild/cloudbuild.yaml
- experimental/terraform/providers.tf
- experimental/terraform/resource_bigquery.tf
This will add cloud build support using impersonation of Terraform service account.
> Cloud build

- experimental/cloudbuild/cloudbuild.yaml
update tfvars so environment.auto.tfvars gets populated correctly
> NAP-275 update tfvars

- experimental/terraform/resource_artifact_registery.tf
NAP-275 create an artifact registry in google cloud
> NAP-275 create artifact registry

- experimental/terraform/resource_artifact_registery.tf
> Nap 275/artifact registry

- event_handler/cloudbuild.yaml
- experimental/cloudbuild/cloudbuild.yaml
- experimental/terraform/resource_event_handler.tf
- experimental/terraform/variables.tf
> Nap 275/cloud build trigger

- experimental/terraform/resource_event_handler.tf
Use var to set the cloudbuild branch name
> NAP-275 use var to set cloudbuild branch

- event_handler/cloudbuild.yaml
use GCR for docker image instead of AR
> NAP-275 use GCR for docker image instead of AR

- event_handler/cloudbuild.yaml
add directory for event_handler cloudbuild
> NAP-275 add directory for event_handler cloudbuild

- event_handler/cloudbuild.yaml
correct directory for event_handler cloudbuild
> NAP-275 correct directory for event_handler cloudbuild

- event_handler/cloudbuild.yaml
- experimental/terraform/resource_event_handler.tf
Ensure build runs on feature branches
> NAP-275/cloud build trigger

- event_handler/cloudbuild.yaml
resolve cloudbuild permissions error
> NAP-275 impersonate terraform SA

- experimental/terraform/data_parser/main.tf
- experimental/terraform/data_parser/variables.tf
- experimental/terraform/resource_artifact_registery.tf
- experimental/terraform/resource_event_handler.tf
- experimental/terraform/resource_parsers.tf
> Nap 275/data parsers

- bq-workers/cloud-build-parser/cloudbuild.yaml
- event_handler/cloudbuild.yaml
- experimental/cloudbuild/cloudbuild.yaml
Create build and push cloud build parser image
> NAP-275/data-parsers

- experimental/terraform/data_parser/main.tf
> NAP-275 update cloud run worker names

- experimental/terraform/data_parser/main.tf
- experimental/terraform/resource_event_handler.tf
NAP-275  ignore changes to image builds
> NAP-275 ignore changes to image

- experimental/terraform/outputs.tf
- experimental/terraform/resource_event_handler.tf
> NAP-275 add domain mapping

- experimental/terraform/resource_event_handler.tf
reference event handler using its ID
> NAP-275 reference event handler using its ID

- experimental/terraform/resource_event_handler.tf
Conditionally use domain mapping region for cloudrun
> NAP-275 conditionally use domain mapping region

- experimental/terraform/outputs.tf
- experimental/terraform/resource_event_handler.tf
Deploy event handler in the same region used for the domain mapping region
> NAP-275 domain mapping

- experimental/terraform/resource_event_handler.tf
> NAP-275/domain mapping

- experimental/terraform/resource_looker.tf
This will correct the policy type to match `iam.disableServiceAccountKeyCreation` requirements
- JIRA: [NAP-255](https://nandosuk.atlassian.net/browse/NAP-275)
> Correct the policy type

- experimental/terraform/resource_looker.tf
This will adjust the Looker Service Account permissions according to Looker [instructions](https://docs.looker.com/setup-and-management/database-config/google-bigquery).
- JIRA: [NAP-275](https://nandosuk.atlassian.net/browse/NAP-275)
> Adjust the Look service account permissions

- experimental/cloudbuild/cloudbuild.yaml
This reverts commit 6d200d3cd3846c8b08ef52cd11fd2811a58c4d02.
> Revert "NAP-275 create fourkeys service account"

- bq-workers/cloud-build-parser/main.py
- event_handler/event_handler.py
update comments in event handler
> NAP-314/cloud build notification

- event_handler/sources.py
This will correct cloud build resource syntax to be able to publish messages.
> Correct cloud build resource syntax

- experimental/cloudbuild/cloudbuild.yaml
add argocd to fourkeys parsers
> NAP-277/add argocd to fourkeys parsers

- experimental/github-webhook/README.md
- experimental/github-webhook/program.py
- experimental/github-webhook/requirements.txt
Add GitHub webhook program to easily add webhooks to Github user/organizations repositories.
> NAP-313/GitHub web hook

- bq-workers/pagerduty-parser/Dockerfile
- bq-workers/pagerduty-parser/cloudbuild.yaml
- bq-workers/pagerduty-parser/main.py
- bq-workers/pagerduty-parser/main_test.py
- bq-workers/pagerduty-parser/requirements-test.txt
- bq-workers/pagerduty-parser/requirements.txt
- event_handler/event_handler.py
- event_handler/sources.py
- experimental/cloudbuild/cloudbuild.yaml
> NAP-281/pagerduty

- event_handler/event_handler.py
- event_handler/sources.py
Overview:
Print statements to log pagerduty request header and body.
> logging to check body

- event_handler/sources.py
Overview:
Updated pager duty secret to retrieve from secret manager.
> Pager duty secret

- event_handler/sources.py
Overview:
Removed encoding of secret to ASCII.
> removed encoding

- event_handler/sources.py
Overview:
Changed comparison of signatures.
> comparing signatures

- bq-workers/pagerduty-parser/main.py
Overview:
Wrong keyword "messages" instead of "message" and some logging.
> removed encoding and logging

- bq-workers/pagerduty-parser/main.py
Overview:
Looping on wrong variable.
> wrong iteration.

- bq-workers/pagerduty-parser/main.py
Overview:
Logging metadata for details.
> metadata check
